server:
  port: 8081

#spring??
spring:
  datasource:
    username: aliyun2028857006
    password: 598949Lytxgz
    url: jdbc:mysql://rm-cn-pe33kbti0000njgo.rwlb.cn-chengdu.rds.aliyuncs.com:3306/online_book_shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    #username: root
    #password: 1234
    #url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER






# mybatis-plus???
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  type-aliases-package: com.atguigu.pojo
  global-config:
    db-config:
      logic-delete-field: isDeleted  #??????
      id-type: auto #???????


#jwt??
jwt:
  token:
    tokenExpiration: 120 #????,????
    tokenSignKey: headline123456  #???????? ???

sky:
  #oss配置
  alioss:
    # 要带上 https:// ,上传时要使用的
    endpoint : https://oss-cn-chengdu.aliyuncs.com

    # 根据自己的帐号配置
    accessKeyId : LTAI5t7FeKrowJ85NXTJLuxp

    # 根据自己的帐号配置
    accessKeySecret : 0SkLNoUz3U2wFRHPRIKyd94HzS6Jsu

    # 存储空间名称
    bucketName : bookstore-picture

    # Bucket域名，访问文件时作为URL前缀，注意要加上 https:// 和 结尾带上 /
    urlPrefix : https://bookstore-picture.oss-cn-chengdu.aliyuncs.com/






