server:
  port: 8080

#spring??
spring:
  datasource:
    username: aliyun2028857006
    password: 598949Lytxgz
    url: jdbc:mysql://rm-cn-pe33kbti0000njgo.rwlb.cn-chengdu.rds.aliyuncs.com:3306/online_book_shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #username: root
    #password: 1234
    #url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER






# mybatis-plus???
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  type-aliases-package: com.atguigu.pojo
  global-config:
    db-config:
      logic-delete-field: isDeleted  #??????
      id-type: auto #???????


#jwt??
jwt:
  token:
    tokenExpiration: 120 #????,????
    tokenSignKey: headline123456  #???????? ???

#oss配置
sky:
  alioss:
    # 要带上 https:// ,上传时要使用的
    endpoint : https://oss-cn-chengdu.aliyuncs.com
    # 根据自己的帐号配置
    accessKeyId : LTAI5t7FeKrowJ85NXTJLuxp
    # 根据自己的帐号配置
    accessKeySecret : 0SkLNoUz3U2wFRHPRIKyd94HzS6Jsu
    # 存储空间名称
    bucketName : bookstore-picture
    # Bucket域名，访问文件时作为URL前缀，注意要加上 https:// 和 结尾带上 /
    urlPrefix : https://bookstore-picture.oss-cn-chengdu.aliyuncs.com/

#支付配置
alipay:
  appId : 9021000134618012
  appPrivateKey : MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCg3LzQpSOp5g2gdA4GHsbU7SntWKuf/sWhtrsGvkwB1RC8wg9sMpzKxJ54zNIc5FNdsY7c21cLpfjl3a4BYYw3S6N9I0xTt9UU6SUlHttSTCzXMlThlEnUiniih//+6fIK9WoOAYeCkaFMNZTI+sK1IxYblHOEyjSTXoD5l7s7nTo6jJZUPSVO8/0sFE28lPk2ENKMk3kDcIZP42NW+y1CCCEogxI2qW/vrMcYdSb/AnA71w3qZEA4it5ersGQIObkFw28FKsX+hV5iohMG4oJW+wSqzgNI4xVTrPY+Cw2b7lhzKFfMdqZIVcQ2vpR3MVmP/w7oWkVDKDH4uyTVDxfAgMBAAECggEABX2jYEfSwNDedDSh6emRBeGWhch6CzsKCewP1DoYpBNev+Kr3hiYK3+snRj4rw3IHrGZ28YM4ZPnvAjmEJwAyj5ltTbIOy9SMaWHpA26lMOO4EWSiiSipIOZfIrB3TSlE2SvGw1IT9eittQ5YObWUJKDBav6iXTReJpIMrzQIke8wbEqa6x7Ib1ZATI9+X7nmoBm1YJE2xM/5w5sAvdWoOo7XHhBbLkN0MkWNlhVNZToQykkCIBvtBdyKeUfgmZQXSpR1Vuw4t4gbkoNjiC2j3McgL+wRK4oBUyWV09y3DXjyGKrN54VOkGAIMxkY1O22FqxFUqaoU7rV1nPADZOcQKBgQDRngkS0ZKiOZHQJ8VPFLHv/EGecDylEb9MRMgwwTrlNayd5AlEaK4PsZYDqkTKUBky4Jj4Q0Fg4AHIz2XtuR6+u55N2+t1VME0V3kukGyk8l3uh/qLINEwqqpjo+tnrouznRROHlwzIcVCraqu+/82+vU43ACyu/v5Gc2KsIGhCQKBgQDEdO0+EHeb5Dv7hFZp6kZ43yxRiCD/9rcuG1HG98kGchwU+4Hw8Jon161dh8LHztODnTpJMPtAyZWHYzFSPDFVMTSLRUPYqOZVsuRk0CMWDRLS3z0XFI4+brh+6PjV9uzVyXmLLmAkn6xfMkN/qonhuQySn90lIod7lxBr1wAUJwKBgE8r4n9yGnEdT16Qduycg2yCGYKvH6i1IEy9OeN4SDdkY3MrOvjUlNGmoGN3/w1u3WWjAQPb2yis0t+2vefg4KTnli4QH0msnmCXnVSiBfby99ltEItV9Mzt2PdTZUk+2tMXRCERRH+nhKrfjzUSRt3MQaydI8JeUBhQz5pPelaJAoGAM/YRQdctK6hkTRQlnwH9/b5ZhH8S62Cf9qv3Jz8mhnPsBYi4R7f7rgoXqqNb22lS/H67idxQuEQZLqQHyY5uJfBLy4JYfZe+xG/6hMegYBa5Idk12ULwlIbIeZi5KC6VWb5eTXfIqicpekxbGgtLSM6fCrEJ1uaZGxFLoJpPRQUCgYEAo95BWb86h324foX/B+mvA7wNKM3hIfGQCC3P30Zd0unrlu8P9Xbdkeekuliazm1Z0gRJofvjsWwwwg/5J/9W01nY0twwhYWhP5gWPHO9dBB4VmBKg/B0GLkbb+LYiry4Xz5PpDpJk+XusUshaO1JoLnK8bHG75pNF7CuQGUo1Vg=
  alipayPublicKey : MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkD48gqBBMdr/p+/C1sEq3XUnROdV9yV5adM3TkzeGXSXnnFbQnf44gOs0j0eCw1EFF3n3nQrjyXVC4UxEaHwUeDIY7uW8lws2meSLMgcRSuVUCwFLc4h4cr7Ac2Iw6s21YfgzNbfV12tSg8PAJlaCbihzer/GBtcSyqOAmJUEMDvrJw3giuiXphGMBDWSwRcsRCYcCX7AnJuD7p4XzVpTrzr+C96B033dODENe8gCsS11GnbukAhJJ27HWwnM6VoIQIMR8OGpr8PCpQixLkaj9HlMuH93rVfI+XGVdgUwjXBwpJoomLx93P7/ZuGqjj1TYiKnj+4zcWZfq1l8aQpPQIDAQAB
  notifyUrl:  http://u5zqdq.natappfree.cc/alipay/notify



